version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g serverless
      - npm install -g yarn
      - yarn
  build:
    commands:
      - yarn deploy:prod

cache:
  paths:
    - node_modules
