version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g serverless
      - npm install -g @serverless/cli
      - npm install -g yarn
      - yarn
  build:
    commands:
      - aws configure set region $AWS_REGION
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - yarn deploy:prod

cache:
  paths:
    - node_modules
