aws-serverless-nextjs:
  component: "@sls-next/serverless-component@3.7.0"
  inputs:
    domain: []
    bucketRegion: ${env.NEXT_PUBLIC_BUCKET_REGION}
    bucketName: ${env.NEXT_PUBLIC_BUCKET_NAME}
    name:
      defaultLambda: ${env.NEXT_PUBLIC_DEFAULT_LAMBDA}
      imageLambda: ${env.NEXT_PUBLIC_IMAGE_LAMBDA}
    cloudfront:
      distributionId: ${env.NEXT_PUBLIC_ClOUDFRONT_ID}
      comment: "nextjs ${env.NEXT_PUBLIC_ENV} deploy"
